#!/usr/bin/env python3
"""
Full-universe Sina XiangGuan feasibility test.

Universe:
  TDX current A-share list (generated by tdx_fetcher.go -mode list)
  +
  SSE/SZSE delisted stocks from AKShare

For every stock code, fetch the Sina XiangGuan page and aggregate
historical membership for the target indexes.

This is deliberately a feasibility test, not production code.
"""

from __future__ import annotations

import json
import os
import re
import sys
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime
from pathlib import Path

import akshare as ak
import pandas as pd
import requests
from bs4 import BeautifulSoup

BASE = "https://vip.stock.finance.sina.com.cn"
ROOT = Path(__file__).resolve().parent
CACHE = ROOT / "sina_xiangguan_cache"
OUT = ROOT / "sina_xiangguan_full_universe"
CACHE.mkdir(parents=True, exist_ok=True)
OUT.mkdir(parents=True, exist_ok=True)

INDEX_ALIASES = {
    "000300": "000300",
    "399300": "000300",
}

TARGET_INDEXES = {
    "000300": "沪深300",
    "000905": "中证500",
    "000852": "中证1000",
    "000688": "科创50",
    "000016": "上证50",
    "399006": "创业板指",
    "932000": "中证2000",
}

WORKERS = int(os.getenv("SINA_WORKERS", "8"))
DELAY = float(os.getenv("SINA_DELAY", "0.15"))
TIMEOUT = 20
RETRIES = 4
UA = (
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/130.0 Safari/537.36"
)


def normalize_code(value: str) -> str:
    s = str(value).strip()
    s = re.sub(r"^(sh|sz|bj)\.?", "", s, flags=re.I)
    return s.zfill(6)


def load_tdx_current() -> pd.DataFrame:
    path = ROOT / "stock_list_master.json"
    if not path.exists():
        raise FileNotFoundError(
            f"Missing {path}; run go run . -mode list first"
        )
    data = json.loads(path.read_text(encoding="utf-8"))
    rows = []
    for item in data:
        code = normalize_code(item.get("code", ""))
        if len(code) == 6:
            rows.append({
                "code": code,
                "name": str(item.get("code_name", "")),
                "source": "tdx_current",
            })
    return pd.DataFrame(rows).drop_duplicates("code")


def load_delisted() -> pd.DataFrame:
    print("Fetching SSE delisted list via AKShare ...", flush=True)
    sh = ak.stock_info_sh_delist()
    print("Fetching SZSE delisted list via AKShare ...", flush=True)
    sz = ak.stock_info_sz_delist(symbol="终止上市公司")

    sh2 = sh.rename(columns={
        "公司代码": "code",
        "公司简称": "name",
        "上市日期": "list_date",
        "暂停上市日期": "delist_date",
    }).copy()
    sh2["exchange"] = "SSE"

    sz2 = sz.rename(columns={
        "证券代码": "code",
        "证券简称": "name",
        "上市日期": "list_date",
        "终止上市日期": "delist_date",
    }).copy()
    sz2["exchange"] = "SZSE"

    for df in (sh2, sz2):
        df["code"] = df["code"].astype(str).str.zfill(6)

    merged = pd.concat([sh2, sz2], ignore_index=True)
    merged = merged.drop_duplicates(subset=["code"]).copy()
    merged["source"] = "delisted"
    return merged[["code", "name", "source", "list_date", "delist_date"]]


def build_universe() -> pd.DataFrame:
    current = load_tdx_current()
    current["list_date"] = ""
    current["delist_date"] = ""

    delisted = load_delisted()

    universe = pd.concat([
        current[["code", "name", "source", "list_date", "delist_date"]],
        delisted[["code", "name", "source", "list_date", "delist_date"]],
    ], ignore_index=True)

    universe["priority"] = universe["source"].map(
        {"tdx_current": 0, "delisted": 1}
    )
    universe = (
        universe.sort_values(["code", "priority"])
        .drop_duplicates("code", keep="first")
        .drop(columns=["priority"])
        .sort_values("code")
        .reset_index(drop=True)
    )
    return universe


def cache_path(code: str) -> Path:
    return CACHE / f"{code}.html"


def fetch_html(session: requests.Session, code: str) -> tuple[str, str]:
    path = cache_path(code)
    if path.exists() and path.stat().st_size > 1000:
        return path.read_text(encoding="gb2312", errors="ignore"), "cache"

    url = f"{BASE}/corp/go.php/vCI_CorpXiangGuan/stockid/{code}.phtml"
    last_error = ""
    for attempt in range(RETRIES):
        try:
            if attempt:
                time.sleep(min(8.0, 0.8 * (2 ** (attempt - 1))))
            r = session.get(url, timeout=TIMEOUT)
            if r.status_code in (403, 429):
                last_error = f"HTTP {r.status_code}"
                continue
            r.raise_for_status()
            r.encoding = "gb2312"
            text = r.text
            if len(text) < 1000:
                last_error = f"short response {len(text)}"
                continue
            path.write_text(text, encoding="gb2312", errors="ignore")
            if DELAY:
                time.sleep(DELAY)
            return text, "network"
        except Exception as exc:
            last_error = repr(exc)
    raise RuntimeError(last_error or "unknown error")


def find_xiangguan_table(soup: BeautifulSoup):
    required = {"指数名称", "指数代码", "进入日期", "退出日期"}
    for table in soup.find_all("table"):
        rows = table.find_all("tr")
        for row in rows[:4]:
            headers = {
                x.get_text(" ", strip=True)
                for x in row.find_all(["th", "td"])
            }
            if required.issubset(headers):
                return table
    return None


def parse_xiangguan(html: str, stock_code: str):
    soup = BeautifulSoup(html, "html.parser")
    table = find_xiangguan_table(soup)
    if table is None:
        return [], "parse_error"

    rows = table.find_all("tr")
    header_idx = None
    headers = []
    for i, row in enumerate(rows[:6]):
        vals = [x.get_text(" ", strip=True) for x in row.find_all(["th", "td"])]
        if {"指数名称", "指数代码", "进入日期", "退出日期"}.issubset(set(vals)):
            header_idx = i
            headers = vals
            break

    if header_idx is None:
        return [], "parse_error"

    pos = {h: i for i, h in enumerate(headers)}
    result = []

    for row in rows[header_idx + 1:]:
        vals = [x.get_text(" ", strip=True) for x in row.find_all(["th", "td"])]
        if len(vals) < len(headers):
            continue

        index_name = vals[pos["指数名称"]].strip()
        index_code = vals[pos["指数代码"]].strip()
        start = vals[pos["进入日期"]].strip()
        end = vals[pos["退出日期"]].strip()

        if not index_code:
            continue

        canonical = INDEX_ALIASES.get(index_code, index_code)
        if canonical not in TARGET_INDEXES:
            continue

        if not re.fullmatch(r"\d{4}-\d{2}-\d{2}", start):
            continue
        if end and not re.fullmatch(r"\d{4}-\d{2}-\d{2}", end):
            continue

        result.append({
            "index_id": canonical,
            "index_name": TARGET_INDEXES[canonical],
            "stock_id": stock_code,
            "start_date": start,
            "end_date": end or "",
            "raw_index_code": index_code,
            "raw_index_name": index_name,
        })

    return result, "ok"


def worker(code: str):
    session = requests.Session()
    session.headers.update({
        "User-Agent": UA,
        "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
    })
    try:
        html, source = fetch_html(session, code)
        rows, status = parse_xiangguan(html, code)
        return code, rows, status, source, ""
    except Exception as exc:
        return code, [], "http_error", "network", repr(exc)


def validate(df: pd.DataFrame):
    errors = []

    if df.empty:
        errors.append("No target-index membership rows were produced")
        return errors

    if df.duplicated(
        ["index_id", "stock_id", "start_date", "end_date"]
    ).any():
        errors.append("Duplicate normalized intervals remain")

    for (idx, stock), g in df.groupby(["index_id", "stock_id"]):
        g = g.sort_values("start_date")
        prev_end = None
        for _, r in g.iterrows():
            start = r["start_date"]
            end = r["end_date"] or None
            if end is not None and start >= end:
                errors.append(
                    f"invalid interval {idx}/{stock}: {start}->{end}"
                )
            if prev_end is not None and start < prev_end:
                errors.append(
                    f"overlap {idx}/{stock}: previous_end={prev_end}, start={start}"
                )
            prev_end = end

    return errors


def pit(df: pd.DataFrame, index_id: str, stock: str, as_of: str) -> bool:
    g = df[(df.index_id == index_id) & (df.stock_id == stock)]
    return any(
        r.start_date <= as_of and (not r.end_date or as_of < r.end_date)
        for r in g.itertuples()
    )


def main():
    started = datetime.utcnow().isoformat() + "Z"

    print("=" * 72)
    print("Sina XiangGuan full-universe feasibility test")
    print("=" * 72)

    universe = build_universe()
    universe.to_csv(
        OUT / "stock_universe.csv",
        index=False,
        encoding="utf-8-sig",
    )

    print(f"TDX current + delisted unique universe = {len(universe)}")
    print(
        f"TDX current count = "
        f"{int((universe.source == 'tdx_current').sum())}"
    )
    print(
        f"Delisted-only count = "
        f"{int((universe.source == 'delisted').sum())}"
    )
    print(f"Workers = {WORKERS}, delay = {DELAY}s")

    all_rows = []
    failures = []
    status_counts = {}
    cache_hits = 0

    codes = universe.code.tolist()
    total = len(codes)

    with ThreadPoolExecutor(max_workers=WORKERS) as ex:
        futures = {ex.submit(worker, code): code for code in codes}
        for n, fut in enumerate(as_completed(futures), 1):
            code, rows, status, source, error = fut.result()
            status_counts[status] = status_counts.get(status, 0) + 1
            if source == "cache":
                cache_hits += 1
            if status == "ok":
                all_rows.extend(rows)
            else:
                failures.append({
                    "code": code,
                    "status": status,
                    "error": error,
                })
            if n % 100 == 0 or n == total:
                print(
                    f"[{n}/{total}] rows={len(all_rows)} "
                    f"failures={len(failures)} cache={cache_hits}",
                    flush=True,
                )

    raw_df = pd.DataFrame(all_rows)
    if not raw_df.empty:
        raw_df = raw_df.drop_duplicates(
            ["index_id", "stock_id", "start_date", "end_date"]
        ).sort_values(
            ["index_id", "stock_id", "start_date", "end_date"]
        ).reset_index(drop=True)

    if raw_df.empty:
        final_df = pd.DataFrame(
            columns=["index_id", "stock_id", "start_date", "end_date"]
        )
    else:
        final_df = raw_df[
            ["index_id", "stock_id", "start_date", "end_date"]
        ].copy()

    raw_df.to_csv(
        OUT / "raw_target_membership.csv",
        index=False,
        encoding="utf-8-sig",
    )
    final_df.to_csv(
        OUT / "index_membership_history.csv",
        index=False,
        encoding="utf-8-sig",
    )
    final_df.to_parquet(
        OUT / "index_membership_history.parquet",
        index=False,
    )

    pd.DataFrame(failures).to_csv(
        OUT / "failed_stocks.csv",
        index=False,
        encoding="utf-8-sig",
    )

    errors = validate(final_df)

    pit_tests = [
        ("000300", "000895", "2005-04-08", True),
        ("000300", "000895", "2007-07-01", True),
        ("000300", "000895", "2007-07-02", False),
        ("000300", "000895", "2008-01-01", False),
        ("000300", "000895", "2008-01-02", True),
        ("000300", "000562", "2005-06-30", True),
        ("000300", "000562", "2005-07-01", False),
        ("000300", "000562", "2006-07-03", True),
        ("000300", "000400", "2013-12-15", False),
        ("000300", "000400", "2013-12-16", True),
        ("000300", "600118", "2021-12-12", True),
        ("000300", "600118", "2021-12-13", False),
        ("000300", "600118", "2026-06-15", True),
    ]

    pit_failed = []
    for idx, stock, date, expected in pit_tests:
        actual = pit(final_df, idx, stock, date)
        print(
            f"PIT {idx}/{stock} @ {date}: "
            f"actual={actual} expected={expected}"
        )
        if actual != expected:
            pit_failed.append((idx, stock, date, actual, expected))

    summary = {
        "started": started,
        "finished": datetime.utcnow().isoformat() + "Z",
        "universe_count": len(universe),
        "tdx_current_count": int(
            (universe.source == "tdx_current").sum()
        ),
        "delisted_only_count": int(
            (universe.source == "delisted").sum()
        ),
        "workers": WORKERS,
        "delay": DELAY,
        "cache_hits": cache_hits,
        "status_counts": status_counts,
        "failed_count": len(failures),
        "raw_target_rows": len(all_rows),
        "normalized_interval_count": len(final_df),
        "index_counts": (
            final_df.groupby("index_id").size().to_dict()
            if not final_df.empty else {}
        ),
        "validation_errors": errors,
        "pit_failed": pit_failed,
        "output_dir": str(OUT),
    }

    (OUT / "summary.json").write_text(
        json.dumps(summary, ensure_ascii=False, indent=2, default=str),
        encoding="utf-8",
    )

    print()
    print("=" * 72)
    print("SUMMARY")
    print("=" * 72)
    print(json.dumps(summary, ensure_ascii=False, indent=2, default=str))

    required = set(TARGET_INDEXES)
    actual = (
        set(final_df.index_id.unique())
        if not final_df.empty else set()
    )
    missing_indexes = sorted(required - actual)

    if failures or errors or pit_failed or missing_indexes:
        if missing_indexes:
            print(f"ERROR: target indexes missing: {missing_indexes}")
        print("FEASIBILITY TEST: FAIL")
        sys.exit(1)

    print("FEASIBILITY TEST: PASS")
    print("Full TDX current + delisted universe -> Sina XiangGuan ->")
    print("target index historical membership is operational.")
    print(f"Artifacts: {OUT}")
    sys.exit(0)


if __name__ == "__main__":
    main()
