#!/usr/bin/env python3
"""
Full-universe Sina XiangGuan feasibility test.

Universe:
  TDX current A-share list (generated by tdx_fetcher.go -mode list)
  +
  SSE/SZSE delisted stocks from AKShare

For every stock code, fetch the Sina XiangGuan page and aggregate
historical membership for the target indexes.

This is deliberately a feasibility test, not production code.
"""

from __future__ import annotations

import json
import os
import re
import sys
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime
from pathlib import Path

import pandas as pd
import requests
from bs4 import BeautifulSoup

BASE = "https://vip.stock.finance.sina.com.cn"
ROOT = Path(__file__).resolve().parent
CACHE = ROOT / "sina_xiangguan_cache"
OUT = ROOT / "sina_xiangguan_full_universe"
CACHE.mkdir(parents=True, exist_ok=True)
OUT.mkdir(parents=True, exist_ok=True)

INDEX_ALIASES = {
    "000300": "000300",
    "399300": "000300",
}

TARGET_INDEXES = {
    "000300": "沪深300",
    "000905": "中证500",
    "000852": "中证1000",
    "000688": "科创50",
    "000016": "上证50",
    "399006": "创业板指",
    "932000": "中证2000",
}

WORKERS = int(os.getenv("SINA_WORKERS", "8"))
DELAY = float(os.getenv("SINA_DELAY", "0.15"))
TIMEOUT = 20
RETRIES = 4
UA = (
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/130.0 Safari/537.36"
)


def normalize_code(value: str) -> str:
    s = str(value).strip()
    s = re.sub(r"^(sh|sz|bj)\.?", "", s, flags=re.I)
    return s.zfill(6)


def load_tdx_current() -> pd.DataFrame:
    path = ROOT / "stock_list_master.json"
    if not path.exists():
        raise FileNotFoundError(
            f"Missing {path}; run go run . -mode list first"
        )
    data = json.loads(path.read_text(encoding="utf-8"))
    rows = []
    for item in data:
        code = normalize_code(item.get("code", ""))
        if len(code) == 6:
            rows.append({
                "code": code,
                "name": str(item.get("code_name", "")),
                "source": "tdx_current",
            })
    return pd.DataFrame(rows).drop_duplicates("code")


def load_delisted() -> pd.DataFrame:
    """Load the user-supplied historical delisted stock universe.

    This test deliberately does not call AKShare. The delisted-code file is
    checked into the test directory and is therefore deterministic/offline.
    """
    path = ROOT / "delisted_stock_codes.txt"
    if not path.exists():
        raise FileNotFoundError(f"Missing supplied delisted list: {path}")

    rows = []
    for line in path.read_text(encoding="utf-8").splitlines():
        code = line.strip()
        if not code or code.startswith("#"):
            continue
        code = normalize_code(code)
        if len(code) != 6 or not code.isdigit():
            raise ValueError(f"Invalid delisted stock code: {code!r}")
        rows.append({
            "code": code,
            "name": "",
            "source": "delisted",
            "list_date": "",
            "delist_date": "",
        })

    return (
        pd.DataFrame(rows)
        .drop_duplicates(subset=["code"])
        .reset_index(drop=True)
    )

def build_universe() -> pd.DataFrame:
    current = load_tdx_current()
    current["list_date"] = ""
    current["delist_date"] = ""

    delisted = load_delisted()

    universe = pd.concat([
        current[["code", "name", "source", "list_date", "delist_date"]],
        delisted[["code", "name", "source", "list_date", "delist_date"]],
    ], ignore_index=True)

    universe["priority"] = universe["source"].map(
        {"tdx_current": 0, "delisted": 1}
    )
    universe = (
        universe.sort_values(["code", "priority"])
        .drop_duplicates("code", keep="first")
        .drop(columns=["priority"])
        .sort_values("code")
        .reset_index(drop=True)
    )
    return universe


def cache_path(code: str) -> Path:
    return CACHE / f"{code}.html"


def fetch_html(session: requests.Session, code: str) -> tuple[str, str]:
    path = cache_path(code)
    if path.exists() and path.stat().st_size > 1000:
        return path.read_text(encoding="gb2312", errors="ignore"), "cache"

    url = f"{BASE}/corp/go.php/vCI_CorpXiangGuan/stockid/{code}.phtml"
    last_error = ""
    for attempt in range(RETRIES):
        try:
            if attempt:
                time.sleep(min(8.0, 0.8 * (2 ** (attempt - 1))))
            r = session.get(url, timeout=TIMEOUT)
            if r.status_code in (403, 429):
                last_error = f"HTTP {r.status_code}"
                continue
            r.raise_for_status()
            r.encoding = "gb2312"
            text = r.text
            if len(text) < 1000:
                last_error = f"short response {len(text)}"
                continue
            path.write_text(text, encoding="gb2312", errors="ignore")
            if DELAY:
                time.sleep(DELAY)
            return text, "network"
        except Exception as exc:
            last_error = repr(exc)
    raise RuntimeError(last_error or "unknown error")


def find_xiangguan_table(soup: BeautifulSoup):
    required = {"指数名称", "指数代码", "进入日期", "退出日期"}
    for table in soup.find_all("table"):
        rows = table.find_all("tr")
        for row in rows[:4]:
            headers = {
                x.get_text(" ", strip=True)
                for x in row.find_all(["th", "td"])
            }
            if required.issubset(headers):
                return table
    return None


def parse_xiangguan(html: str, stock_code: str):
    soup = BeautifulSoup(html, "html.parser")
    table = find_xiangguan_table(soup)
    if table is None:
        return [], "parse_error"

    rows = table.find_all("tr")
    header_idx = None
    headers = []
    for i, row in enumerate(rows[:6]):
        vals = [x.get_text(" ", strip=True) for x in row.find_all(["th", "td"])]
        if {"指数名称", "指数代码", "进入日期", "退出日期"}.issubset(set(vals)):
            header_idx = i
            headers = vals
            break

    if header_idx is None:
        return [], "parse_error"

    pos = {h: i for i, h in enumerate(headers)}
    result = []

    for row in rows[header_idx + 1:]:
        vals = [x.get_text(" ", strip=True) for x in row.find_all(["th", "td"])]
        if len(vals) < len(headers):
            continue

        index_name = vals[pos["指数名称"]].strip()
        index_code = vals[pos["指数代码"]].strip()
        start = vals[pos["进入日期"]].strip()
        end = vals[pos["退出日期"]].strip()

        if not index_code:
            continue

        canonical = INDEX_ALIASES.get(index_code, index_code)
        if canonical not in TARGET_INDEXES:
            continue

        if not re.fullmatch(r"\d{4}-\d{2}-\d{2}", start):
            continue
        if end and not re.fullmatch(r"\d{4}-\d{2}-\d{2}", end):
            continue

        result.append({
            "index_id": canonical,
            "index_name": TARGET_INDEXES[canonical],
            "stock_id": stock_code,
            "start_date": start,
            "end_date": end or "",
            "raw_index_code": index_code,
            "raw_index_name": index_name,
        })

    return result, "ok"



def fetch_component_page(
    session: requests.Session,
    index_id: str,
    kind: str,
    page: int,
) -> str:
    path = (
        "vII_HistoryComponent.php"
        if kind == "history"
        else "vII_NewestComponent.php"
    )
    url = f"{BASE}/corp/view/{path}?page={page}&indexid={index_id}"
    r = session.get(url, timeout=TIMEOUT)
    r.raise_for_status()
    r.encoding = "gb2312"
    return r.text


def component_page_count(html: str) -> int:
    pages = [int(x) for x in re.findall(r"[?&]page=(\d+)", html)]
    return max(pages, default=1)


def parse_component_codes(html: str) -> set[str]:
    soup = BeautifulSoup(html, "html.parser")
    for table in soup.find_all("table"):
        rows = table.find_all("tr")
        for row in rows[:6]:
            headers = [
                x.get_text(" ", strip=True)
                for x in row.find_all(["th", "td"])
            ]
            if "品种代码" not in headers:
                continue

            code_pos = headers.index("品种代码")
            codes = set()
            for data_row in rows[rows.index(row) + 1:]:
                vals = [
                    x.get_text(" ", strip=True)
                    for x in data_row.find_all(["th", "td"])
                ]
                if len(vals) <= code_pos:
                    continue
                code = normalize_code(vals[code_pos])
                if re.fullmatch(r"\d{6}", code):
                    codes.add(code)
            if codes:
                return codes
    return set()


def collect_a_candidates() -> tuple[dict[str, set[str]], list[dict]]:
    """
    Build A = HistoryComponent ∪ NewestComponent candidate stocks.

    This only discovers candidate stock codes. The actual historical
    intervals are still parsed from the same XiangGuan pages used by B,
    so the A/B comparison has identical normalization semantics.
    """
    session = requests.Session()
    session.headers.update({
        "User-Agent": UA,
        "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
    })

    candidates = {}
    errors = []

    for index_id in TARGET_INDEXES:
        codes = set()
        for kind in ("history", "newest"):
            try:
                first = fetch_component_page(session, index_id, kind, 1)
                pages = component_page_count(first)
                for page in range(1, pages + 1):
                    html = (
                        first
                        if page == 1
                        else fetch_component_page(
                            session, index_id, kind, page
                        )
                    )
                    codes.update(parse_component_codes(html))
                print(
                    f"A candidates {index_id} {kind}: "
                    f"pages={pages} stocks={len(codes)}",
                    flush=True,
                )
            except Exception as exc:
                errors.append({
                    "index_id": index_id,
                    "kind": kind,
                    "error": repr(exc),
                })

        candidates[index_id] = codes
        print(
            f"A candidates {index_id}: union={len(codes)}",
            flush=True,
        )

    return candidates, errors


def build_a_from_xiangguan(
    candidates: dict[str, set[str]],
) -> tuple[pd.DataFrame, list[dict]]:
    """
    Convert A candidate stocks into normalized intervals.

    Reuse the B XiangGuan cache whenever possible. If A discovers a stock
    that was not present in the B universe, fetch that stock page here.
    """
    rows = []
    errors = []
    session = requests.Session()
    session.headers.update({
        "User-Agent": UA,
        "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
    })

    all_codes = sorted(set().union(*candidates.values()))
    for n, code in enumerate(all_codes, 1):
        try:
            html, _ = fetch_html(session, code)
            parsed, status = parse_xiangguan(html, code)
            if status != "ok":
                errors.append({
                    "code": code,
                    "status": status,
                    "error": "XiangGuan parse failed for A candidate",
                })
                continue

            wanted = set()
            for index_id, codes in candidates.items():
                if code in codes:
                    wanted.add(index_id)

            rows.extend(
                row for row in parsed
                if row["index_id"] in wanted
            )
        except Exception as exc:
            errors.append({
                "code": code,
                "status": "http_error",
                "error": repr(exc),
            })

        if n % 100 == 0 or n == len(all_codes):
            print(
                f"A XiangGuan [{n}/{len(all_codes)}] "
                f"intervals={len(rows)} errors={len(errors)}",
                flush=True,
            )

    columns = ["index_id", "stock_id", "start_date", "end_date"]
    df = pd.DataFrame(rows)
    if df.empty:
        df = pd.DataFrame(columns=columns)
    else:
        df = (
            df[columns]
            .drop_duplicates()
            .sort_values(columns)
            .reset_index(drop=True)
        )
    return df, errors


def run_ab_diff(
    a_df: pd.DataFrame,
    b_df: pd.DataFrame,
) -> dict:
    diff_dir = OUT / "ab_diff"
    diff_dir.mkdir(parents=True, exist_ok=True)
    key = ["index_id", "stock_id", "start_date", "end_date"]

    summary_rows = []
    all_a_only = []
    all_b_only = []

    for index_id in TARGET_INDEXES:
        a = a_df[a_df.index_id == index_id][key].drop_duplicates()
        b = b_df[b_df.index_id == index_id][key].drop_duplicates()

        merged = a.merge(
            b,
            on=key,
            how="outer",
            indicator=True,
        )
        a_only = (
            merged[merged["_merge"] == "left_only"]
            .drop(columns="_merge")
            .sort_values(key)
        )
        b_only = (
            merged[merged["_merge"] == "right_only"]
            .drop(columns="_merge")
            .sort_values(key)
        )

        a_only.to_csv(
            diff_dir / f"{index_id}_a_minus_b.csv",
            index=False,
            encoding="utf-8-sig",
        )
        b_only.to_csv(
            diff_dir / f"{index_id}_b_minus_a.csv",
            index=False,
            encoding="utf-8-sig",
        )

        for frame, side in ((a_only, "A-B"), (b_only, "B-A")):
            if not frame.empty:
                temp = frame.copy()
                temp["diff"] = side
                if side == "A-B":
                    all_a_only.append(temp)
                else:
                    all_b_only.append(temp)

        a_stocks = set(a.stock_id)
        b_stocks = set(b.stock_id)
        summary_rows.append({
            "index_id": index_id,
            "a_intervals": len(a),
            "b_intervals": len(b),
            "a_only_intervals": len(a_only),
            "b_only_intervals": len(b_only),
            "a_stocks": len(a_stocks),
            "b_stocks": len(b_stocks),
            "a_only_stocks": len(a_stocks - b_stocks),
            "b_only_stocks": len(b_stocks - a_stocks),
        })

    summary_df = pd.DataFrame(summary_rows)
    summary_df.to_csv(
        diff_dir / "all_indices_diff_summary.csv",
        index=False,
        encoding="utf-8-sig",
    )

    a_all = (
        pd.concat(all_a_only, ignore_index=True)
        if all_a_only
        else pd.DataFrame(columns=key + ["diff"])
    )
    b_all = (
        pd.concat(all_b_only, ignore_index=True)
        if all_b_only
        else pd.DataFrame(columns=key + ["diff"])
    )
    a_all.to_csv(
        diff_dir / "all_a_minus_b.csv",
        index=False,
        encoding="utf-8-sig",
    )
    b_all.to_csv(
        diff_dir / "all_b_minus_a.csv",
        index=False,
        encoding="utf-8-sig",
    )

    return {
        "summary": summary_rows,
        "a_minus_b_intervals": len(a_all),
        "b_minus_a_intervals": len(b_all),
        "diff_dir": str(diff_dir),
    }


def worker(code: str):
    session = requests.Session()
    session.headers.update({
        "User-Agent": UA,
        "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
    })
    try:
        html, source = fetch_html(session, code)
        rows, status = parse_xiangguan(html, code)
        return code, rows, status, source, ""
    except Exception as exc:
        return code, [], "http_error", "network", repr(exc)


def validate(df: pd.DataFrame):
    errors = []

    if df.empty:
        errors.append("No target-index membership rows were produced")
        return errors

    if df.duplicated(
        ["index_id", "stock_id", "start_date", "end_date"]
    ).any():
        errors.append("Duplicate normalized intervals remain")

    for (idx, stock), g in df.groupby(["index_id", "stock_id"]):
        g = g.sort_values("start_date")
        prev_end = None
        for _, r in g.iterrows():
            start = r["start_date"]
            end = r["end_date"] or None
            if end is not None and start >= end:
                errors.append(
                    f"invalid interval {idx}/{stock}: {start}->{end}"
                )
            if prev_end is not None and start < prev_end:
                errors.append(
                    f"overlap {idx}/{stock}: previous_end={prev_end}, start={start}"
                )
            prev_end = end

    return errors


def pit(df: pd.DataFrame, index_id: str, stock: str, as_of: str) -> bool:
    g = df[(df.index_id == index_id) & (df.stock_id == stock)]
    return any(
        r.start_date <= as_of and (not r.end_date or as_of < r.end_date)
        for r in g.itertuples()
    )


def main():
    started = datetime.utcnow().isoformat() + "Z"

    print("=" * 72)
    print("Sina XiangGuan full-universe feasibility test")
    print("=" * 72)

    universe = build_universe()
    universe.to_csv(
        OUT / "stock_universe.csv",
        index=False,
        encoding="utf-8-sig",
    )

    print(f"TDX current + delisted unique universe = {len(universe)}")
    print(
        f"TDX current count = "
        f"{int((universe.source == 'tdx_current').sum())}"
    )
    print(
        f"Delisted-only count = "
        f"{int((universe.source == 'delisted').sum())}"
    )
    print(f"Workers = {WORKERS}, delay = {DELAY}s")

    all_rows = []
    failures = []
    status_counts = {}
    cache_hits = 0

    codes = universe.code.tolist()
    total = len(codes)

    with ThreadPoolExecutor(max_workers=WORKERS) as ex:
        futures = {ex.submit(worker, code): code for code in codes}
        for n, fut in enumerate(as_completed(futures), 1):
            code, rows, status, source, error = fut.result()
            status_counts[status] = status_counts.get(status, 0) + 1
            if source == "cache":
                cache_hits += 1
            if status == "ok":
                all_rows.extend(rows)
            else:
                failures.append({
                    "code": code,
                    "status": status,
                    "error": error,
                })
            if n % 100 == 0 or n == total:
                print(
                    f"[{n}/{total}] rows={len(all_rows)} "
                    f"failures={len(failures)} cache={cache_hits}",
                    flush=True,
                )

    raw_df = pd.DataFrame(all_rows)
    if not raw_df.empty:
        raw_df = raw_df.drop_duplicates(
            ["index_id", "stock_id", "start_date", "end_date"]
        ).sort_values(
            ["index_id", "stock_id", "start_date", "end_date"]
        ).reset_index(drop=True)

    if raw_df.empty:
        final_df = pd.DataFrame(
            columns=["index_id", "stock_id", "start_date", "end_date"]
        )
    else:
        final_df = raw_df[
            ["index_id", "stock_id", "start_date", "end_date"]
        ].copy()

    raw_df.to_csv(
        OUT / "raw_target_membership.csv",
        index=False,
        encoding="utf-8-sig",
    )
    final_df.to_csv(
        OUT / "index_membership_history.csv",
        index=False,
        encoding="utf-8-sig",
    )
    final_df.to_parquet(
        OUT / "index_membership_history.parquet",
        index=False,
    )

    pd.DataFrame(failures).to_csv(
        OUT / "failed_stocks.csv",
        index=False,
        encoding="utf-8-sig",
    )

    errors = validate(final_df)

    print()
    print("=" * 72)
    print("A/B COMPLETENESS DIFF")
    print("=" * 72)

    a_candidates, a_candidate_errors = collect_a_candidates()
    a_df, a_xiangguan_errors = build_a_from_xiangguan(a_candidates)

    a_df.to_csv(
        OUT / "ab_a_index_membership_history.csv",
        index=False,
        encoding="utf-8-sig",
    )
    a_df.to_parquet(
        OUT / "ab_a_index_membership_history.parquet",
        index=False,
    )

    ab_result = run_ab_diff(a_df, final_df)

    print(
        f"A normalized intervals = {len(a_df)}, "
        f"B normalized intervals = {len(final_df)}"
    )
    print(
        f"A-B intervals = {ab_result['a_minus_b_intervals']}, "
        f"B-A intervals = {ab_result['b_minus_a_intervals']}"
    )
    print(json.dumps(ab_result["summary"], ensure_ascii=False, indent=2))

    pit_tests = [
        ("000300", "000895", "2005-04-08", True),
        ("000300", "000895", "2007-07-01", True),
        ("000300", "000895", "2007-07-02", False),
        ("000300", "000895", "2008-01-01", False),
        ("000300", "000895", "2008-01-02", True),
        ("000300", "000562", "2005-06-30", True),
        ("000300", "000562", "2005-07-01", False),
        ("000300", "000562", "2006-07-03", True),
        ("000300", "000400", "2013-12-15", False),
        ("000300", "000400", "2013-12-16", True),
        ("000300", "600118", "2021-12-12", True),
        ("000300", "600118", "2021-12-13", False),
        ("000300", "600118", "2026-06-15", True),
    ]

    pit_failed = []
    for idx, stock, date, expected in pit_tests:
        actual = pit(final_df, idx, stock, date)
        print(
            f"PIT {idx}/{stock} @ {date}: "
            f"actual={actual} expected={expected}"
        )
        if actual != expected:
            pit_failed.append((idx, stock, date, actual, expected))

    summary = {
        "started": started,
        "finished": datetime.utcnow().isoformat() + "Z",
        "universe_count": len(universe),
        "tdx_current_count": int(
            (universe.source == "tdx_current").sum()
        ),
        "delisted_only_count": int(
            (universe.source == "delisted").sum()
        ),
        "workers": WORKERS,
        "delay": DELAY,
        "cache_hits": cache_hits,
        "status_counts": status_counts,
        "failed_count": len(failures),
        "raw_target_rows": len(all_rows),
        "normalized_interval_count": len(final_df),
        "index_counts": (
            final_df.groupby("index_id").size().to_dict()
            if not final_df.empty else {}
        ),
        "validation_errors": errors,
        "pit_failed": pit_failed,
        "ab": {
            "candidate_errors": a_candidate_errors,
            "xiangguan_errors": a_xiangguan_errors,
            **ab_result,
        },
        "output_dir": str(OUT),
    }

    (OUT / "summary.json").write_text(
        json.dumps(summary, ensure_ascii=False, indent=2, default=str),
        encoding="utf-8",
    )

    print()
    print("=" * 72)
    print("SUMMARY")
    print("=" * 72)
    print(json.dumps(summary, ensure_ascii=False, indent=2, default=str))

    required = set(TARGET_INDEXES)
    actual = (
        set(final_df.index_id.unique())
        if not final_df.empty else set()
    )
    missing_indexes = sorted(required - actual)

    if (
        failures
        or errors
        or pit_failed
        or missing_indexes
        or a_candidate_errors
        or a_xiangguan_errors
    ):
        if missing_indexes:
            print(f"ERROR: target indexes missing: {missing_indexes}")
        print("FEASIBILITY TEST: FAIL")
        sys.exit(1)

    print("FEASIBILITY TEST: PASS")
    print("Full TDX current + delisted universe -> Sina XiangGuan ->")
    print("target index historical membership is operational.")
    print(f"Artifacts: {OUT}")
    sys.exit(0)


if __name__ == "__main__":
    main()
