#!/usr/bin/env python3
"""
Full-universe Sina XiangGuan feasibility test.

Universe:
  TDX current A-share list (generated by tdx_fetcher.go -mode list)
  +
  SSE/SZSE delisted stocks from AKShare

For every stock code, fetch the Sina XiangGuan page and aggregate
historical membership for the target indexes.

This is deliberately a feasibility test, not production code.
"""

from __future__ import annotations

import json
import os
import re
import sys
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime
from pathlib import Path

import pandas as pd
import requests
from bs4 import BeautifulSoup

BASE = "https://vip.stock.finance.sina.com.cn"
ROOT = Path(__file__).resolve().parent
CACHE = ROOT / "sina_xiangguan_cache"
PARSED_CACHE = ROOT / "sina_xiangguan_parsed_cache"
OUT = ROOT / "sina_xiangguan_full_universe"
CACHE.mkdir(parents=True, exist_ok=True)
PARSED_CACHE.mkdir(parents=True, exist_ok=True)
OUT.mkdir(parents=True, exist_ok=True)

INDEX_ALIASES = {
    "000001": "000001", "399001": "399001", "399006": "399006",
    "000688": "000688", "899050": "899050", "000016": "000016",
    "000300": "000300", "399300": "000300", "000905": "000905", "399905": "000905",
    "000852": "000852", "399852": "000852", "000851": "000851", "932000": "000851",
    "399303": "399303", "399330": "399330", "000090": "000090", "399324": "399324",
    "000015": "000015", "000827": "000827", "399317": "399317", "399807": "399807",
    "399812": "399812", "399354": "399354", "399673": "399673", "399285": "399285",
    "399008": "399008", "399993": "399993", "399975": "399975", "399986": "399986",
    "399932": "399932", "399933": "399933", "399967": "399967", "399989": "399989",
    "399971": "399971", "399997": "399997", "000934": "000934", "000935": "000935",
    "399990": "399990", "399998": "399998", "399974": "399974",
}

TARGET_INDEXES = {
    "000001": "上证指数", "399001": "深证成指", "399006": "创业板指",
    "000688": "科创50", "899050": "北证50", "000016": "上证50",
    "000300": "沪深300", "000905": "中证500", "000852": "中证1000",
    "000851": "中证2000", "399303": "国证2000", "399330": "深证100",
    "000090": "上证180", "399324": "深证红利", "000015": "红利指数",
    "000827": "中证中盘", "399317": "国证1000", "399807": "中证人工智能",
    "399812": "国证芯片", "399354": "国证人工智能", "399673": "创业板50",
    "399285": "国证新能源", "399008": "中小100", "399993": "中证信息安全",
    "399975": "证券公司", "399986": "中证银行", "399932": "中证消费",
    "399933": "中证医药", "399967": "中证军工", "399989": "中证医疗",
    "399971": "中证传媒", "399997": "中证白酒", "000934": "中证能源",
    "000935": "中证原材料", "399990": "煤炭等权", "399998": "中证有色",
    "399974": "国证国企",
}

SINA_COMPONENT_INDEX_IDS = {"000851": "932000"}

WORKERS = int(os.getenv("SINA_WORKERS", "8"))
DELAY = float(os.getenv("SINA_DELAY", "0.15"))
TIMEOUT = 20
RETRIES = 4
UA = (
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/130.0 Safari/537.36"
)


def normalize_code(value: str) -> str:
    s = str(value).strip()
    s = re.sub(r"^(sh|sz|bj)\.?", "", s, flags=re.I)
    return s.zfill(6)


def load_tdx_current() -> pd.DataFrame:
    path = ROOT / "stock_list_master.json"
    if not path.exists():
        raise FileNotFoundError(
            f"Missing {path}; run go run . -mode list first"
        )
    data = json.loads(path.read_text(encoding="utf-8"))
    rows = []
    for item in data:
        code = normalize_code(item.get("code", ""))
        if len(code) == 6:
            rows.append({
                "code": code,
                "name": str(item.get("code_name", "")),
                "source": "tdx_current",
            })
    return pd.DataFrame(rows).drop_duplicates("code")


def load_delisted() -> pd.DataFrame:
    """Load the user-supplied historical delisted stock universe.

    This test deliberately does not call AKShare. The delisted-code file is
    checked into the test directory and is therefore deterministic/offline.
    """
    path = ROOT / "delisted_stock_codes.txt"
    if not path.exists():
        raise FileNotFoundError(f"Missing supplied delisted list: {path}")

    rows = []
    for line in path.read_text(encoding="utf-8").splitlines():
        code = line.strip()
        if not code or code.startswith("#"):
            continue
        code = normalize_code(code)
        if len(code) != 6 or not code.isdigit():
            raise ValueError(f"Invalid delisted stock code: {code!r}")
        rows.append({
            "code": code,
            "name": "",
            "source": "delisted",
            "list_date": "",
            "delist_date": "",
        })

    return (
        pd.DataFrame(rows)
        .drop_duplicates(subset=["code"])
        .reset_index(drop=True)
    )

def build_universe() -> pd.DataFrame:
    current = load_tdx_current()
    current["list_date"] = ""
    current["delist_date"] = ""

    delisted = load_delisted()

    universe = pd.concat([
        current[["code", "name", "source", "list_date", "delist_date"]],
        delisted[["code", "name", "source", "list_date", "delist_date"]],
    ], ignore_index=True)

    universe["priority"] = universe["source"].map(
        {"tdx_current": 0, "delisted": 1}
    )
    universe = (
        universe.sort_values(["code", "priority"])
        .drop_duplicates("code", keep="first")
        .drop(columns=["priority"])
        .sort_values("code")
        .reset_index(drop=True)
    )
    return universe


def cache_path(code: str) -> Path:
    return CACHE / f"{code}.html"


def parsed_cache_path(code: str) -> Path:
    return PARSED_CACHE / f"{code}.json"


def load_parsed_cache(code: str):
    path = parsed_cache_path(code)
    if not path.exists() or path.stat().st_size == 0:
        return None
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
        if payload.get("version") != 1 or payload.get("stock_id") != code:
            return None
        rows = payload.get("rows")
        status = payload.get("status")
        if not isinstance(rows, list) or status not in {"ok", "parse_error"}:
            return None
        return rows, status
    except Exception:
        return None


def save_parsed_cache(code: str, rows, status: str):
    parsed_cache_path(code).write_text(
        json.dumps(
            {"version": 1, "stock_id": code, "status": status, "rows": rows},
            ensure_ascii=False,
            separators=(",", ":"),
        ),
        encoding="utf-8",
    )


def fetch_html(session: requests.Session, code: str) -> tuple[str, str]:
    path = cache_path(code)
    if path.exists() and path.stat().st_size > 1000:
        return path.read_text(encoding="gb2312", errors="ignore"), "cache"

    url = f"{BASE}/corp/go.php/vCI_CorpXiangGuan/stockid/{code}.phtml"
    last_error = ""
    for attempt in range(RETRIES):
        try:
            if attempt:
                time.sleep(min(8.0, 0.8 * (2 ** (attempt - 1))))
            r = session.get(url, timeout=TIMEOUT)
            if r.status_code in (403, 429):
                last_error = f"HTTP {r.status_code}"
                continue
            r.raise_for_status()
            r.encoding = "gb2312"
            text = r.text
            if len(text) < 1000:
                last_error = f"short response {len(text)}"
                continue
            path.write_text(text, encoding="gb2312", errors="ignore")
            if DELAY:
                time.sleep(DELAY)
            return text, "network"
        except Exception as exc:
            last_error = repr(exc)
    raise RuntimeError(last_error or "unknown error")


def find_xiangguan_table(soup: BeautifulSoup):
    required = {"指数名称", "指数代码", "进入日期", "退出日期"}
    for table in soup.find_all("table"):
        rows = table.find_all("tr")
        for row in rows[:4]:
            headers = {
                x.get_text(" ", strip=True)
                for x in row.find_all(["th", "td"])
            }
            if required.issubset(headers):
                return table
    return None


def parse_xiangguan(html: str, stock_code: str):
    soup = BeautifulSoup(html, "html.parser")
    table = find_xiangguan_table(soup)
    if table is None:
        return [], "parse_error"

    rows = table.find_all("tr")
    header_idx = None
    headers = []
    for i, row in enumerate(rows[:6]):
        vals = [x.get_text(" ", strip=True) for x in row.find_all(["th", "td"])]
        if {"指数名称", "指数代码", "进入日期", "退出日期"}.issubset(set(vals)):
            header_idx = i
            headers = vals
            break

    if header_idx is None:
        return [], "parse_error"

    pos = {h: i for i, h in enumerate(headers)}
    result = []

    for row in rows[header_idx + 1:]:
        vals = [x.get_text(" ", strip=True) for x in row.find_all(["th", "td"])]
        if len(vals) < len(headers):
            continue

        index_name = vals[pos["指数名称"]].strip()
        index_code = vals[pos["指数代码"]].strip()
        start = vals[pos["进入日期"]].strip()
        end = vals[pos["退出日期"]].strip()

        if not index_code:
            continue

        canonical = INDEX_ALIASES.get(index_code, index_code)
        if canonical not in TARGET_INDEXES:
            continue

        if not re.fullmatch(r"\d{4}-\d{2}-\d{2}", start):
            continue
        if end and not re.fullmatch(r"\d{4}-\d{2}-\d{2}", end):
            continue

        result.append({
            "index_id": canonical,
            "index_name": TARGET_INDEXES[canonical],
            "stock_id": stock_code,
            "start_date": start,
            "end_date": end or "",
            "raw_index_code": index_code,
            "raw_index_name": index_name,
        })

    return result, "ok"



def fetch_component_page(
    session: requests.Session,
    index_id: str,
    kind: str,
    page: int,
) -> str:
    path = (
        "vII_HistoryComponent.php"
        if kind == "history"
        else "vII_NewestComponent.php"
    )
    query_index_id = SINA_COMPONENT_INDEX_IDS.get(index_id, index_id)
    url = f"{BASE}/corp/view/{path}?page={page}&indexid={query_index_id}"
    r = session.get(url, timeout=TIMEOUT)
    r.raise_for_status()
    r.encoding = "gb2312"
    return r.text


def component_page_count(html: str) -> int:
    pages = [int(x) for x in re.findall(r"[?&]page=(\d+)", html)]
    return max(pages, default=1)


def parse_component_codes(html: str) -> set[str]:
    soup = BeautifulSoup(html, "html.parser")
    for table in soup.find_all("table"):
        rows = table.find_all("tr")
        for row in rows[:6]:
            headers = [
                x.get_text(" ", strip=True)
                for x in row.find_all(["th", "td"])
            ]
            if "品种代码" not in headers:
                continue

            code_pos = headers.index("品种代码")
            codes = set()
            for data_row in rows[rows.index(row) + 1:]:
                vals = [
                    x.get_text(" ", strip=True)
                    for x in data_row.find_all(["th", "td"])
                ]
                if len(vals) <= code_pos:
                    continue
                code = normalize_code(vals[code_pos])
                if re.fullmatch(r"\d{6}", code):
                    codes.add(code)
            if codes:
                return codes
    return set()


def collect_a_candidates() -> tuple[dict[str, set[str]], list[dict]]:
    """
    Build A = HistoryComponent ∪ NewestComponent candidate stocks.

    This only discovers candidate stock codes. The actual historical
    intervals are still parsed from the same XiangGuan pages used by B,
    so the A/B comparison has identical normalization semantics.
    """
    session = requests.Session()
    session.headers.update({
        "User-Agent": UA,
        "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
    })

    candidates = {}
    errors = []

    for index_id in TARGET_INDEXES:
        codes = set()
        for kind in ("history", "newest"):
            try:
                first = fetch_component_page(session, index_id, kind, 1)
                pages = component_page_count(first)
                for page in range(1, pages + 1):
                    html = (
                        first
                        if page == 1
                        else fetch_component_page(
                            session, index_id, kind, page
                        )
                    )
                    codes.update(parse_component_codes(html))
                print(
                    f"A candidates {index_id} {kind}: "
                    f"pages={pages} stocks={len(codes)}",
                    flush=True,
                )
            except Exception as exc:
                errors.append({
                    "index_id": index_id,
                    "kind": kind,
                    "error": repr(exc),
                })

        candidates[index_id] = codes
        print(
            f"A candidates {index_id}: union={len(codes)}",
            flush=True,
        )

    return candidates, errors


def build_a_from_xiangguan(
    candidates: dict[str, set[str]],
) -> tuple[pd.DataFrame, list[dict]]:
    """
    Convert A candidate stocks into normalized intervals.

    Reuse the B XiangGuan cache whenever possible. If A discovers a stock
    that was not present in the B universe, fetch that stock page here.
    """
    rows = []
    errors = []
    session = requests.Session()
    session.headers.update({
        "User-Agent": UA,
        "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
    })

    all_codes = sorted(set().union(*candidates.values()))
    for n, code in enumerate(all_codes, 1):
        try:
            cached = load_parsed_cache(code)
            if cached is None:
                html, _ = fetch_html(session, code)
                parsed, status = parse_xiangguan(html, code)
                save_parsed_cache(code, parsed, status)
            else:
                parsed, status = cached
            if status != "ok":
                errors.append({
                    "code": code,
                    "status": status,
                    "error": "XiangGuan parse failed for A candidate",
                })
                continue

            wanted = set()
            for index_id, codes in candidates.items():
                if code in codes:
                    wanted.add(index_id)

            rows.extend(
                row for row in parsed
                if row["index_id"] in wanted
            )
        except Exception as exc:
            errors.append({
                "code": code,
                "status": "http_error",
                "error": repr(exc),
            })

        if n % 100 == 0 or n == len(all_codes):
            print(
                f"A XiangGuan [{n}/{len(all_codes)}] "
                f"intervals={len(rows)} errors={len(errors)}",
                flush=True,
            )

    columns = ["index_id", "stock_id", "start_date", "end_date"]
    df = pd.DataFrame(rows)
    if df.empty:
        df = pd.DataFrame(columns=columns)
    else:
        df = (
            df[columns]
            .drop_duplicates()
            .sort_values(columns)
            .reset_index(drop=True)
        )
    return df, errors


def run_ab_diff(
    a_df: pd.DataFrame,
    b_df: pd.DataFrame,
) -> dict:
    diff_dir = OUT / "ab_diff"
    diff_dir.mkdir(parents=True, exist_ok=True)
    key = ["index_id", "stock_id", "start_date", "end_date"]

    summary_rows = []
    all_a_only = []
    all_b_only = []

    for index_id in TARGET_INDEXES:
        a = a_df[a_df.index_id == index_id][key].drop_duplicates()
        b = b_df[b_df.index_id == index_id][key].drop_duplicates()

        merged = a.merge(
            b,
            on=key,
            how="outer",
            indicator=True,
        )
        a_only = (
            merged[merged["_merge"] == "left_only"]
            .drop(columns="_merge")
            .sort_values(key)
        )
        b_only = (
            merged[merged["_merge"] == "right_only"]
            .drop(columns="_merge")
            .sort_values(key)
        )

        a_only.to_csv(
            diff_dir / f"{index_id}_a_minus_b.csv",
            index=False,
            encoding="utf-8-sig",
        )
        b_only.to_csv(
            diff_dir / f"{index_id}_b_minus_a.csv",
            index=False,
            encoding="utf-8-sig",
        )

        for frame, side in ((a_only, "A-B"), (b_only, "B-A")):
            if not frame.empty:
                temp = frame.copy()
                temp["diff"] = side
                if side == "A-B":
                    all_a_only.append(temp)
                else:
                    all_b_only.append(temp)

        a_stocks = set(a.stock_id)
        b_stocks = set(b.stock_id)
        summary_rows.append({
            "index_id": index_id,
            "a_intervals": len(a),
            "b_intervals": len(b),
            "a_only_intervals": len(a_only),
            "b_only_intervals": len(b_only),
            "a_stocks": len(a_stocks),
            "b_stocks": len(b_stocks),
            "a_only_stocks": len(a_stocks - b_stocks),
            "b_only_stocks": len(b_stocks - a_stocks),
        })

    summary_df = pd.DataFrame(summary_rows)
    summary_df.to_csv(
        diff_dir / "all_indices_diff_summary.csv",
        index=False,
        encoding="utf-8-sig",
    )

    a_all = (
        pd.concat(all_a_only, ignore_index=True)
        if all_a_only
        else pd.DataFrame(columns=key + ["diff"])    )
    b_all = (
        pd.concat(all_b_only, ignore_index=True)
        if all_b_only
        else pd.DataFrame(columns=key + ["diff"])
    )
    a_all.to_csv(
        diff_dir / "all_a_minus_b.csv",
        index=False,
        encoding="utf-8-sig",
    )
    b_all.to_csv(
        diff_dir / "all_b_minus_a.csv",
        index=False,
        encoding="utf-8-sig",
    )

    return {
        "summary": summary_rows,
        "a_minus_b_intervals": len(a_all),
        "b_minus_a_intervals": len(b_all),
        "diff_dir": str(diff_dir),
    }



def audit_b_only(
    a_df: pd.DataFrame,
    b_df: pd.DataFrame,
    universe: pd.DataFrame,
) -> dict:
    """Audit intervals found by B but missed by A candidate discovery."""
    audit_dir = OUT / "ab_diff"
    audit_dir.mkdir(parents=True, exist_ok=True)
    key = ["index_id", "stock_id", "start_date", "end_date"]

    a_keys = set(map(tuple, a_df[key].itertuples(index=False, name=None)))
    b_tuples = b_df[key].apply(tuple, axis=1)
    b_only = b_df[~b_tuples.isin(a_keys)][key].copy()

    source_map = universe.set_index("code")["source"].to_dict()

    if b_only.empty:
        detail = pd.DataFrame(columns=[
            *key, "source", "interval_count_for_stock",
            "first_start_for_stock", "last_end_for_stock",
        ])
    else:
        counts = b_only.groupby(["index_id", "stock_id"]).size().rename(
            "interval_count_for_stock"
        )
        first_start = b_only.groupby(["index_id", "stock_id"])["start_date"].min().rename(
            "first_start_for_stock"
        )
        last_end = b_only.groupby(["index_id", "stock_id"])["end_date"].max().rename(
            "last_end_for_stock"
        )
        detail = b_only.merge(counts.reset_index(), on=["index_id", "stock_id"])
        detail = detail.merge(first_start.reset_index(), on=["index_id", "stock_id"])
        detail = detail.merge(last_end.reset_index(), on=["index_id", "stock_id"])
        detail["source"] = detail["stock_id"].map(source_map).fillna("unknown")
        detail = detail.sort_values(
            ["index_id", "first_start_for_stock", "stock_id", "start_date"]
        ).reset_index(drop=True)

    summary_rows = []
    for index_id in TARGET_INDEXES:
        g = detail[detail.index_id == index_id]
        stocks = set(g.stock_id)
        summary_rows.append({
            "index_id": index_id,
            "b_only_intervals": len(g),
            "b_only_stocks": len(stocks),
            "current_stocks": sum(source_map.get(x) == "tdx_current" for x in stocks),
            "delisted_only_stocks": sum(source_map.get(x) == "delisted" for x in stocks),
            "earliest_start": g.start_date.min() if not g.empty else "",
            "latest_start": g.start_date.max() if not g.empty else "",
            "open_ended_intervals": int((g.end_date == "").sum()) if not g.empty else 0,
        })
    summary = pd.DataFrame(summary_rows)

    detail.to_csv(audit_dir / "b_only_stock_audit.csv", index=False, encoding="utf-8-sig")
    summary.to_csv(audit_dir / "b_only_summary.csv", index=False, encoding="utf-8-sig")

    samples = []
    for index_id in TARGET_INDEXES:
        g = detail[detail.index_id == index_id]
        for label, sg in (
            ("earliest", g.sort_values(["start_date", "stock_id"]).head(10)),
            ("latest", g.sort_values(["start_date", "stock_id"], ascending=False).head(10)),
            ("open_ended", g[g.end_date == ""].sort_values(["start_date", "stock_id"]).head(10)),
        ):
            if not sg.empty:
                samples.append(sg.assign(sample=label))
    sample_df = (
        pd.concat(samples, ignore_index=True)
        if samples else detail.head(0).assign(sample=pd.Series(dtype=str))
    )
    sample_df.to_csv(
        audit_dir / "b_only_representative_samples.csv",
        index=False,
        encoding="utf-8-sig",
    )

    a_only = []
    for index_id in TARGET_INDEXES:
        a = a_df[a_df.index_id == index_id][key].drop_duplicates()
        b = b_df[b_df.index_id == index_id][key].drop_duplicates()
        merged = a.merge(b, on=key, how="outer", indicator=True)
        x = merged[merged["_merge"] == "left_only"].drop(columns="_merge")
        if not x.empty:
            a_only.append(x)
    a_only_df = pd.concat(a_only, ignore_index=True) if a_only else pd.DataFrame(columns=key)
    a_only_df.to_csv(
        audit_dir / "a_only_intervals_detail.csv",
        index=False,
        encoding="utf-8-sig",
    )

    print()
    print("=" * 72)
    print("B-ONLY AUDIT")
    print("=" * 72)
    print(summary.to_string(index=False))

    return {
        "b_only_intervals": len(detail),
        "b_only_stocks": int(detail.stock_id.nunique()) if not detail.empty else 0,
        "summary": summary.to_dict(orient="records"),
        "audit_files": [
            str(audit_dir / "b_only_stock_audit.csv"),
            str(audit_dir / "b_only_summary.csv"),
            str(audit_dir / "b_only_representative_samples.csv"),
            str(audit_dir / "a_only_intervals_detail.csv"),
        ],
    }



EXPECTED_MEMBER_COUNTS = {
    "000300": 300, "000905": 500, "000852": 1000,
    "000688": 50, "000016": 50, "399006": 100, "000851": 2000,
}




def audit_adjustment_boundaries(df: pd.DataFrame) -> dict:
    """Audit PIT entry/exit boundaries efficiently.

    Verifies the half-open interval semantics:
        start_date <= as_of < end_date

    The audit uses pre-built per-(index, stock) interval maps and aggregate
    adjustment-date counts, avoiding repeated whole-DataFrame filtering.
    """
    audit_dir = OUT / "quality_audit"
    audit_dir.mkdir(parents=True, exist_ok=True)

    work = df.copy()
    if work.empty:
        return {"status": "FAIL", "error_count": 1, "reason": "empty membership dataframe"}

    work["start_date_dt"] = pd.to_datetime(work["start_date"])
    work["end_date_dt"] = pd.to_datetime(
        work["end_date"].replace("", pd.NA), errors="coerce"
    )

    # Build once: each stock has only its own intervals.
    interval_map = {}
    for (index_id, stock_id), g in work.groupby(["index_id", "stock_id"], sort=False):
        intervals = [
            (r.start_date_dt, r.end_date_dt)
            for r in g.itertuples(index=False)
        ]
        interval_map[(index_id, stock_id)] = intervals

    def member_on(index_id: str, stock_id: str, date: pd.Timestamp) -> bool:
        """O(1)-ish lookup over this stock's small interval list."""
        for start, end in interval_map.get((index_id, stock_id), ()):
            if start <= date and (pd.isna(end) or date < end):
                return True
        return False

    checks = []
    failures = []

    # Entry checks.
    entry_rows = work[
        ["index_id", "stock_id", "start_date_dt"]
    ].itertuples(index=False)
    entry_total = len(work)
    for n, row in enumerate(entry_rows, 1):
        start = row.start_date_dt
        before = start - pd.Timedelta(days=1)
        before_actual = member_on(row.index_id, row.stock_id, before)
        on_actual = member_on(row.index_id, row.stock_id, start)
        ok = (not before_actual) and on_actual
        item = {
            "index_id": row.index_id,
            "stock_id": row.stock_id,
            "change_type": "entry",
            "change_date": start.strftime("%Y-%m-%d"),
            "probe_date_before": before.strftime("%Y-%m-%d"),
            "probe_date_on": start.strftime("%Y-%m-%d"),
            "before_member": before_actual,
            "on_member": on_actual,
            "expected_before": False,
            "expected_on": True,
            "status": "PASS" if ok else "FAIL",
        }
        checks.append(item)
        if not ok:
            failures.append(item)
        if n % 2000 == 0 or n == entry_total:
            print(
                f"Boundary audit: entry checks {n}/{entry_total} "
                f"failures={len(failures)}",
                flush=True,
            )

    # Exit checks.
    exit_rows = work[
        work["end_date_dt"].notna()
    ][["index_id", "stock_id", "end_date_dt"]].itertuples(index=False)
    exit_total = int(work["end_date_dt"].notna().sum())
    for n, row in enumerate(exit_rows, 1):
        end = row.end_date_dt
        before = end - pd.Timedelta(days=1)
        before_actual = member_on(row.index_id, row.stock_id, before)
        on_actual = member_on(row.index_id, row.stock_id, end)
        ok = before_actual and (not on_actual)
        item = {
            "index_id": row.index_id,
            "stock_id": row.stock_id,
            "change_type": "exit",
            "change_date": end.strftime("%Y-%m-%d"),
            "probe_date_before": before.strftime("%Y-%m-%d"),
            "probe_date_on": end.strftime("%Y-%m-%d"),
            "before_member": before_actual,
            "on_member": on_actual,
            "expected_before": True,
            "expected_on": False,
            "status": "PASS" if ok else "FAIL",
        }
        checks.append(item)
        if not ok:
            failures.append(item)
        if n % 2000 == 0 or n == exit_total:
            print(
                f"Boundary audit: exit checks {n}/{exit_total} "
                f"failures={len(failures)}",
                flush=True,
            )

    checks_df = pd.DataFrame(checks)
    failures_df = pd.DataFrame(failures)
    if failures_df.empty:
        failures_df = checks_df.head(0).copy()

    checks_df.to_csv(
        audit_dir / "adjustment_boundary_checks.csv",
        index=False,
        encoding="utf-8-sig",
    )
    failures_df.to_csv(
        audit_dir / "adjustment_boundary_failures.csv",
        index=False,
        encoding="utf-8-sig",
    )

    # Aggregate adjustment-day transitions directly from interval boundaries.
    # For each date:
    #   before_count = prior active count
    #   on_count     = before_count + entries - exits
    transition_rows = []
    for index_id, g in work.groupby("index_id", sort=True):
        starts = (
            g.groupby("start_date_dt")
            .size()
            .rename("added_count")
        )
        exits = (
            g[g["end_date_dt"].notna()]
            .groupby("end_date_dt")
            .size()
            .rename("removed_count")
        )
        changes = pd.concat([starts, exits], axis=1).fillna(0).astype(int).reset_index()
        changes = changes.rename(columns={"index": "change_date"})
        changes = changes.sort_values("change_date")

        # Establish the count immediately before the first boundary from
        # interval membership, then update incrementally thereafter.
        dates = changes["change_date"].tolist()
        all_stocks = set(g["stock_id"])
        first_date = dates[0]
        before_date = first_date - pd.Timedelta(days=1)
        before_count = sum(
            member_on(index_id, stock_id, before_date)
            for stock_id in all_stocks
        )

        for row in changes.itertuples(index=False):
            change_date = row.change_date
            added_count = int(row.added_count)
            removed_count = int(row.removed_count)
            on_count = before_count + added_count - removed_count

            added = g[
                g["start_date_dt"] == change_date
            ]["stock_id"].tolist()
            removed = g[
                g["end_date_dt"] == change_date
            ]["stock_id"].tolist()

            transition_rows.append({
                "index_id": index_id,
                "change_date": change_date.strftime("%Y-%m-%d"),
                "before_count": before_count,
                "on_count": on_count,
                "delta": on_count - before_count,
                "added_count": added_count,
                "removed_count": removed_count,
                "added_stocks": ",".join(sorted(added)),
                "removed_stocks": ",".join(sorted(removed)),
            })
            before_count = on_count

    transitions_df = pd.DataFrame(transition_rows)
    transitions_df.to_csv(
        audit_dir / "adjustment_day_transitions.csv",
        index=False,
        encoding="utf-8-sig",
    )

    # Independent transition consistency check:
    # before + added - removed must equal on.
    transition_failures = transitions_df[
        transitions_df["before_count"] +
        transitions_df["added_count"] -
        transitions_df["removed_count"] != transitions_df["on_count"]
    ].copy()
    transition_failures.to_csv(
        audit_dir / "adjustment_transition_failures.csv",
        index=False,
        encoding="utf-8-sig",
    )

    summary_rows = []
    for index_id in TARGET_INDEXES:
        cg = checks_df[checks_df.index_id == index_id]
        tg = transitions_df[transitions_df.index_id == index_id]
        summary_rows.append({
            "index_id": index_id,
            "entry_checks": int((cg.change_type == "entry").sum()),
            "exit_checks": int((cg.change_type == "exit").sum()),
            "failed_checks": int((cg.status == "FAIL").sum()),
            "adjustment_days": len(tg),
            "transition_min_before": int(tg.before_count.min()) if not tg.empty else "",
            "transition_max_before": int(tg.before_count.max()) if not tg.empty else "",
            "transition_min_on": int(tg.on_count.min()) if not tg.empty else "",
            "transition_max_on": int(tg.on_count.max()) if not tg.empty else "",
        })

    summary_df = pd.DataFrame(summary_rows)
    summary_df.to_csv(
        audit_dir / "adjustment_boundary_summary.csv",
        index=False,
        encoding="utf-8-sig",
    )

    print()
    print("=" * 72)
    print("MEMBER ENTRY/EXIT ADJUSTMENT-DAY BOUNDARY AUDIT")
    print("=" * 72)
    print(summary_df.to_string(index=False))
    print("Boundary checks =", len(checks_df))
    print("Boundary failures =", len(failures_df))
    print("Transition consistency failures =", len(transition_failures))
    print("Adjustment days =", len(transitions_df))

    return {
        "status": (
            "PASS"
            if failures_df.empty and transition_failures.empty
            else "FAIL"
        ),
        "check_count": len(checks_df),
        "failure_count": len(failures_df),
        "transition_failure_count": len(transition_failures),
        "failures_by_index": (
            failures_df.groupby("index_id").size().to_dict()
            if not failures_df.empty else {}
        ),
        "summary": summary_df.to_dict(orient="records"),
        "files": [
            str(audit_dir / "adjustment_boundary_checks.csv"),
            str(audit_dir / "adjustment_boundary_failures.csv"),
            str(audit_dir / "adjustment_day_transitions.csv"),
            str(audit_dir / "adjustment_transition_failures.csv"),
            str(audit_dir / "adjustment_boundary_summary.csv"),
        ],
    }


def audit_membership_quality(
    df: pd.DataFrame,
    universe: pd.DataFrame,
    a_df: pd.DataFrame,
) -> dict:
    """Offline structural/PIT quality audit; network-free."""
    audit_dir = OUT / "quality_audit"
    audit_dir.mkdir(parents=True, exist_ok=True)

    key = ["index_id", "stock_id", "start_date", "end_date"]
    work = df.copy()
    if work.empty:
        return {"status": "FAIL", "reason": "empty membership dataframe"}

    work["start_date_dt"] = pd.to_datetime(work["start_date"])
    work["end_date_dt"] = pd.to_datetime(
        work["end_date"].replace("", pd.NA), errors="coerce"
    )

    # Explicit interval integrity check.
    overlap_rows = []
    for (idx, stock), g in work.groupby(["index_id", "stock_id"]):
        g = g.sort_values(["start_date_dt", "end_date_dt"], na_position="last")
        prev_end = None
        for _, r in g.iterrows():
            start = r["start_date_dt"]
            end = r["end_date_dt"]
            if pd.notna(end) and start >= end:
                overlap_rows.append({
                    "index_id": idx, "stock_id": stock,
                    "start_date": r["start_date"], "end_date": r["end_date"],
                    "type": "invalid_interval",
                    "previous_end": "",
                })
            if prev_end is not None and start < prev_end:
                overlap_rows.append({
                    "index_id": idx, "stock_id": stock,
                    "start_date": r["start_date"], "end_date": r["end_date"],
                    "type": "overlap",
                    "previous_end": prev_end.strftime("%Y-%m-%d"),
                })
            prev_end = end if pd.notna(end) else pd.Timestamp.max

    overlap_df = pd.DataFrame(overlap_rows)
    if overlap_df.empty:
        overlap_df = pd.DataFrame(columns=[
            "index_id", "stock_id", "start_date", "end_date",
            "type", "previous_end",
        ])
    overlap_df.to_csv(
        audit_dir / "interval_overlap_errors.csv",
        index=False, encoding="utf-8-sig",
    )

    # Daily PIT member counts. Deviations are WARN diagnostics, not FAIL.
    count_rows = []
    anomaly_rows = []
    for index_id, g in work.groupby("index_id"):
        min_date = g["start_date_dt"].min()
        max_end = g["end_date_dt"].max()
        max_date = (
            max_end
            if pd.notna(max_end)
            else pd.Timestamp.now("UTC").tz_localize(None).normalize()
        )
        expected = EXPECTED_MEMBER_COUNTS.get(index_id)
        for date in pd.date_range(min_date, max_date, freq="D"):
            starts = g["start_date_dt"].to_numpy()
            ends = g["end_date_dt"].to_numpy()
            count = int(((starts <= date) & (
                pd.isna(ends) | (date < ends)
            )).sum())
            row = {
                "index_id": index_id,
                "date": date.strftime("%Y-%m-%d"),
                "member_count": count,
                "expected": expected if expected else "",
                "ratio": round(count / expected, 4) if expected else "",
            }
            count_rows.append(row)
            if expected and (
                count < expected * 0.80 or count > expected * 1.20
            ):
                anomaly_rows.append({**row, "severity": "WARN"})

    counts_df = pd.DataFrame(count_rows)
    if not counts_df.empty:
        counts_df["previous_member_count"] = (
            counts_df.groupby("index_id")["member_count"].shift(1)
        )
        counts_df["next_member_count"] = (
            counts_df.groupby("index_id")["member_count"].shift(-1)
        )
    anomalies_df = pd.DataFrame(anomaly_rows)
    if anomalies_df.empty:
        anomalies_df = pd.DataFrame(columns=[
            "index_id", "date", "member_count", "expected",
            "ratio", "severity",
        ])
    counts_df.to_csv(
        audit_dir / "daily_member_counts.csv",
        index=False, encoding="utf-8-sig",
    )
    if not anomalies_df.empty:
        anomalies_df = counts_df[
            counts_df["index_id"].isin(anomalies_df["index_id"])
            & counts_df["date"].isin(anomalies_df["date"])
        ].copy()
    else:
        anomalies_df = counts_df.head(0).copy()

    # 399006 initialization-stage observations are informational only.
    init_info_mask = (
        (anomalies_df["index_id"] == "399006")
        & anomalies_df["date"].isin(["2010-06-01", "2010-06-02"])
    )
    initialization_rows = anomalies_df[init_info_mask].copy()
    if not initialization_rows.empty:
        initialization_rows["severity"] = "INFO"
        initialization_rows["reason"] = "index_initialization_phase"
        initialization_rows.to_csv(
            audit_dir / "399006_initialization_info.csv",
            index=False, encoding="utf-8-sig",
        )
        print("399006 initialization-stage member-count INFO:")
        print(initialization_rows.to_string(index=False))

    anomalies_df = anomalies_df[~init_info_mask].copy()
    anomalies_df["severity"] = "WARN"
    anomalies_df.to_csv(
        audit_dir / "member_count_anomalies.csv",
        index=False, encoding="utf-8-sig",
    )

    anomaly_context_rows = []
    for _, row in anomalies_df[anomalies_df["index_id"] == "399006"].iterrows():
        d = pd.Timestamp(row["date"])
        ctx = counts_df[
            (counts_df["index_id"] == "399006")
            & counts_df["date"].between(
                (d - pd.Timedelta(days=2)).strftime("%Y-%m-%d"),
                (d + pd.Timedelta(days=2)).strftime("%Y-%m-%d"),
            )
        ].copy()
        ctx["anomaly_date"] = row["date"]
        anomaly_context_rows.append(ctx)
    anomaly_context = (
        pd.concat(anomaly_context_rows, ignore_index=True).drop_duplicates()
        if anomaly_context_rows else counts_df.head(0).copy()
    )
    anomaly_context.to_csv(
        audit_dir / "399006_anomaly_context.csv",
        index=False, encoding="utf-8-sig",
    )
    if not anomalies_df[anomalies_df["index_id"] == "399006"].empty:
        print("399006 anomaly details:")
        print(anomalies_df[anomalies_df["index_id"] == "399006"].to_string(index=False))
        print("399006 anomaly context:")
        print(anomaly_context.to_string(index=False))

    stats_rows = []
    for index_id, g in counts_df.groupby("index_id"):
        s = g["member_count"]
        stats_rows.append({
            "index_id": index_id,
            "expected": EXPECTED_MEMBER_COUNTS.get(index_id, ""),
            "min": int(s.min()),
            "p01": float(s.quantile(0.01)),
            "median": float(s.median()),
            "p99": float(s.quantile(0.99)),
            "max": int(s.max()),
            "anomaly_days": int(
                len(anomalies_df[anomalies_df.index_id == index_id])
            ),
        })
    stats_df = pd.DataFrame(stats_rows)
    stats_df.to_csv(
        audit_dir / "member_count_stats.csv",
        index=False, encoding="utf-8-sig",
    )

    # Dedicated 932000 audit.
    g932 = work[work.index_id == "000851"].copy()
    open932 = g932[g932.end_date == ""].copy()
    open_by_month = (
        open932.assign(
            start_month=open932.start_date_dt.dt.to_period("M").astype(str)
        )
        .groupby("start_month")
        .size()
        .reset_index(name="open_ended_intervals")
        if not open932.empty
        else pd.DataFrame(columns=["start_month", "open_ended_intervals"])
    )
    open_by_month.to_csv(
        audit_dir / "000851_open_ended_by_month.csv",
        index=False, encoding="utf-8-sig",
    )
    open932[["index_id", "stock_id", "start_date", "end_date"]].sort_values(
        ["start_date", "stock_id"]
    ).head(100).to_csv(
        audit_dir / "000851_open_ended_samples.csv",
        index=False, encoding="utf-8-sig",
    )

    # A-only detail with source/name.
    a_keys = set(map(tuple, a_df[key].itertuples(index=False, name=None)))
    b_keys = set(map(tuple, df[key].itertuples(index=False, name=None)))
    a_only = a_df[
        a_df[key].apply(tuple, axis=1).isin(a_keys - b_keys)
    ][key].drop_duplicates()
    source_map = universe.set_index("code")["source"].to_dict()
    name_map = universe.set_index("code")["name"].to_dict()
    if not a_only.empty:
        a_only = a_only.copy()
        a_only["stock_name"] = a_only["stock_id"].map(name_map).fillna("")
        a_only["universe_source"] = a_only["stock_id"].map(
            source_map
        ).fillna("unknown")
    a_only.to_csv(
        audit_dir / "a_only_detailed.csv",
        index=False, encoding="utf-8-sig",
    )

    quality_rows = []
    for index_id in TARGET_INDEXES:
        cg = counts_df[counts_df.index_id == index_id]
        og = overlap_df[overlap_df.index_id == index_id]
        qg = anomalies_df[anomalies_df.index_id == index_id]
        quality_rows.append({
            "index_id": index_id,
            "expected": EXPECTED_MEMBER_COUNTS.get(index_id, ""),
            "min": int(cg.member_count.min()) if not cg.empty else "",
            "median": float(cg.member_count.median()) if not cg.empty else "",
            "max": int(cg.member_count.max()) if not cg.empty else "",
            "anomaly_days": len(qg),
            "overlap_or_invalid": len(og),
            "open_ended_intervals": int(
                ((work.index_id == index_id) & (work.end_date == "")).sum()
            ),
        })
    quality_df = pd.DataFrame(quality_rows)
    quality_df.to_csv(
        audit_dir / "quality_summary.csv",
        index=False, encoding="utf-8-sig",
    )

    print()
    print("=" * 72)
    print("MEMBERSHIP QUALITY AUDIT")
    print("=" * 72)
    print(quality_df.to_string(index=False))
    print("Interval overlap/invalid errors =", len(overlap_df))
    print("Member-count diagnostic WARN days =", len(anomalies_df))
    print("000851/932000 open-ended intervals =", len(open932))
    print("A-only intervals =", len(a_only))

    return {
        "status": "PASS" if overlap_df.empty else "FAIL",
        "overlap_count": len(overlap_df),
        "overlap_by_index": (
            overlap_df.groupby("index_id").size().to_dict()
            if not overlap_df.empty else {}
        ),
        "count_anomaly_rows": len(anomalies_df),
        "count_anomaly_by_index": (
            anomalies_df.groupby("index_id").size().to_dict()
            if not anomalies_df.empty else {}
        ),
        "399006_initialization_info_rows": len(initialization_rows),
        "member_count_stats": stats_df.to_dict(orient="records"),
        "open_ended_000851": len(open932),
        "open_ended_000851_by_month": dict(zip(
            open_by_month.start_month,
            open_by_month.open_ended_intervals,
        )),
        "a_only_intervals": len(a_only),
        "files": [
            str(audit_dir / "interval_overlap_errors.csv"),
            str(audit_dir / "daily_member_counts.csv"),
            str(audit_dir / "member_count_anomalies.csv"),
            str(audit_dir / "399006_initialization_info.csv"),
            str(audit_dir / "member_count_stats.csv"),
            str(audit_dir / "399006_anomaly_context.csv"),
            str(audit_dir / "000851_open_ended_by_month.csv"),
            str(audit_dir / "000851_open_ended_samples.csv"),
            str(audit_dir / "a_only_detailed.csv"),
            str(audit_dir / "quality_summary.csv"),
        ],
    }

def worker(code: str):
    # Prefer structured parsed cache. This avoids both HTTP and BeautifulSoup
    # work on subsequent runs.
    cached = load_parsed_cache(code)
    if cached is not None:
        rows, status = cached
        return code, rows, status, "parsed_cache", ""

    session = requests.Session()
    session.headers.update({
        "User-Agent": UA,
        "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
    })
    try:
        html, source = fetch_html(session, code)
        rows, status = parse_xiangguan(html, code)
        save_parsed_cache(code, rows, status)
        return code, rows, status, source, ""
    except Exception as exc:
        return code, [], "http_error", "network", repr(exc)


def validate(df: pd.DataFrame):
    errors = []

    if df.empty:
        errors.append("No target-index membership rows were produced")
        return errors

    if df.duplicated(
        ["index_id", "stock_id", "start_date", "end_date"]
    ).any():
        errors.append("Duplicate normalized intervals remain")

    for (idx, stock), g in df.groupby(["index_id", "stock_id"]):
        g = g.sort_values("start_date")
        prev_end = None
        for _, r in g.iterrows():
            start = r["start_date"]
            end = r["end_date"] or None
            if end is not None and start >= end:
                errors.append(
                    f"invalid interval {idx}/{stock}: {start}->{end}"
                )
            if prev_end is not None and start < prev_end:
                errors.append(
                    f"overlap {idx}/{stock}: previous_end={prev_end}, start={start}"
                )
            prev_end = end

    return errors


def pit(df: pd.DataFrame, index_id: str, stock: str, as_of: str) -> bool:
    g = df[(df.index_id == index_id) & (df.stock_id == stock)]
    return any(
        r.start_date <= as_of and (not r.end_date or as_of < r.end_date)
        for r in g.itertuples()
    )


def main():
    started = datetime.utcnow().isoformat() + "Z"

    print("=" * 72)
    print("Sina XiangGuan full-universe feasibility test")
    print("=" * 72)

    universe = build_universe()
    universe.to_csv(
        OUT / "stock_universe.csv",
        index=False,
        encoding="utf-8-sig",
    )

    print(f"TDX current + delisted unique universe = {len(universe)}")
    print(
        f"TDX current count = "
        f"{int((universe.source == 'tdx_current').sum())}"
    )
    print(
        f"Delisted-only count = "
        f"{int((universe.source == 'delisted').sum())}"
    )
    print(f"Workers = {WORKERS}, delay = {DELAY}s")

    all_rows = []
    failures = []
    status_counts = {}
    cache_hits = 0
    parsed_cache_hits = 0
    network_fetches = 0
    started_fetch = time.perf_counter()

    codes = universe.code.tolist()
    total = len(codes)

    with ThreadPoolExecutor(max_workers=WORKERS) as ex:
        futures = {ex.submit(worker, code): code for code in codes}
        for n, fut in enumerate(as_completed(futures), 1):
            code, rows, status, source, error = fut.result()
            status_counts[status] = status_counts.get(status, 0) + 1
            if source == "cache":
                cache_hits += 1
            elif source == "parsed_cache":
                parsed_cache_hits += 1
            elif source == "network":
                network_fetches += 1
            if status == "ok":
                all_rows.extend(rows)
            else:
                failures.append({
                    "code": code,
                    "status": status,
                    "error": error,
                })
            if n % 100 == 0 or n == total:
                print(
                    f"[{n}/{total}] rows={len(all_rows)} "
                    f"failures={len(failures)} cache={cache_hits}",
                    flush=True,
                )

    raw_df = pd.DataFrame(all_rows)
    if not raw_df.empty:
        raw_df = raw_df.drop_duplicates(
            ["index_id", "stock_id", "start_date", "end_date"]
        ).sort_values(
            ["index_id", "stock_id", "start_date", "end_date"]
        ).reset_index(drop=True)

    if raw_df.empty:
        final_df = pd.DataFrame(
            columns=["index_id", "stock_id", "start_date", "end_date"]
        )
    else:
        final_df = raw_df[
            ["index_id", "stock_id", "start_date", "end_date"]
        ].copy()

    raw_df.to_csv(
        OUT / "raw_target_membership.csv",
        index=False,
        encoding="utf-8-sig",
    )
    final_df.to_csv(
        OUT / "index_membership_history.csv",
        index=False,
        encoding="utf-8-sig",
    )
    final_df.to_parquet(
        OUT / "index_membership_history.parquet",
        index=False,
    )

    pd.DataFrame(failures).to_csv(
        OUT / "failed_stocks.csv",
        index=False,
        encoding="utf-8-sig",
    )

    errors = validate(final_df)

    print()
    print("=" * 72)
    print("A/B COMPLETENESS DIFF")
    print("=" * 72)

    a_candidates, a_candidate_errors = collect_a_candidates()
    a_df, a_xiangguan_errors = build_a_from_xiangguan(a_candidates)

    a_df.to_csv(
        OUT / "ab_a_index_membership_history.csv",
        index=False,
        encoding="utf-8-sig",
    )
    a_df.to_parquet(
        OUT / "ab_a_index_membership_history.parquet",
        index=False,
    )

    ab_result = run_ab_diff(a_df, final_df)
    b_only_audit = audit_b_only(a_df, final_df, universe)
    quality_audit = audit_membership_quality(final_df, universe, a_df)
    boundary_audit = audit_adjustment_boundaries(final_df)
    ab_result["b_only_audit"] = b_only_audit
    ab_result["quality_audit"] = quality_audit
    ab_result["boundary_audit"] = boundary_audit

    print(
        f"A normalized intervals = {len(a_df)}, "
        f"B normalized intervals = {len(final_df)}"
    )
    print(
        f"A-B intervals = {ab_result['a_minus_b_intervals']}, "
        f"B-A intervals = {ab_result['b_minus_a_intervals']}"
    )
    print(json.dumps(ab_result["summary"], ensure_ascii=False, indent=2))

    pit_tests = [
        ("000300", "000895", "2005-04-08", True),
        ("000300", "000895", "2007-07-01", True),
        ("000300", "000895", "2007-07-02", False),
        ("000300", "000895", "2008-01-01", False),
        ("000300", "000895", "2008-01-02", True),
        ("000300", "000562", "2005-06-30", True),
        ("000300", "000562", "2005-07-01", False),
        ("000300", "000562", "2006-07-03", True),
        ("000300", "000400", "2013-12-15", False),
        ("000300", "000400", "2013-12-16", True),
        ("000300", "600118", "2021-12-12", True),
        ("000300", "600118", "2021-12-13", False),
        ("000300", "600118", "2026-06-15", True),
    ]

    pit_failed = []
    for idx, stock, date, expected in pit_tests:
        actual = pit(final_df, idx, stock, date)
        print(
            f"PIT {idx}/{stock} @ {date}: "
            f"actual={actual} expected={expected}"
        )
        if actual != expected:
            pit_failed.append((idx, stock, date, actual, expected))

    summary = {
        "started": started,
        "finished": datetime.utcnow().isoformat() + "Z",
        "universe_count": len(universe),
        "tdx_current_count": int(
            (universe.source == "tdx_current").sum()
        ),
        "delisted_only_count": int(
            (universe.source == "delisted").sum()
        ),
        "workers": WORKERS,
        "delay": DELAY,
        "cache_hits": cache_hits,
        "parsed_cache_hits": parsed_cache_hits,
        "network_fetches": network_fetches,
        "fetch_phase_seconds": round(time.perf_counter() - started_fetch, 3),
        "status_counts": status_counts,
        "failed_count": len(failures),
        "raw_target_rows": len(all_rows),
        "normalized_interval_count": len(final_df),
        "index_counts": (
            final_df.groupby("index_id").size().to_dict()
            if not final_df.empty else {}
        ),
        "validation_errors": errors,
        "pit_failed": pit_failed,
        "ab": {
            "candidate_errors": a_candidate_errors,
            "xiangguan_errors": a_xiangguan_errors,
            **ab_result,
        },
        "output_dir": str(OUT),
    }

    (OUT / "summary.json").write_text(
        json.dumps(summary, ensure_ascii=False, indent=2, default=str),
        encoding="utf-8",
    )

    print()
    print("=" * 72)
    print("SUMMARY")
    print("=" * 72)
    print(json.dumps(summary, ensure_ascii=False, indent=2, default=str))

    required = set(TARGET_INDEXES)
    actual = (
        set(final_df.index_id.unique())
        if not final_df.empty else set()
    )
    missing_indexes = sorted(required - actual)

    if (
        failures
        or errors
        or pit_failed
        or missing_indexes
        or a_candidate_errors
        or a_xiangguan_errors
        or quality_audit["status"] == "FAIL"
        or boundary_audit["status"] == "FAIL"
    ):
        if missing_indexes:
            print(f"ERROR: target indexes missing: {missing_indexes}")
        print("FEASIBILITY TEST: FAIL")
        sys.exit(1)

    print("FEASIBILITY TEST: PASS")
    print("Full TDX current + delisted universe -> Sina XiangGuan ->")
    print("target index historical membership is operational.")
    print(f"Artifacts: {OUT}")
    sys.exit(0)


if __name__ == "__main__":
    main()